services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:80"
    depends_on:
      - db
      - searcher

  controller:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
    volumes:
      - db_data:/var/lib/mysql

  searcher:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"
    depends_on:
      - api

volumes:
  db_data:
